#!/usr/bin/env python
# coding: utf-8

# In[4]:

import datetime

import pandas as pd

import seaborn as snd 

import matplotlib as plt

import numpy as np

#In[11]


last_active='last active'
print(last_active)

print()

now = datetime.datetime.now()

print(now)
